### PR TITLE
[WIP] [iOS] Admin Dashboard Enhancements

### PR DESCRIPTION
**Pull request by JPKribs**
### Formerly
https://github.com/jellyfin/Swiftfin/pull/1255

### Issue
This is an extension of https://github.com/jellyfin/Swiftfin/pull/1230

### Summary
This PR is where I have a couple different branches living together. I need to split them out into more manageable PRs but I wanted to make this visible so it wasn't just me working in the shadows. All of the Goals below are in this branch with varying levels of polish. As items are done, I'll check them off below.

### Goals
- [x] Fix PlayMethod DirectPlay vs DirectStream not mirroring Web | https://github.com/jellyfin/Swiftfin/pull/1272
- [x] Add device icons to Active Devices without NowPlayingItems | https://github.com/jellyfin/Swiftfin/pull/1275
- [x] Finish EditScheduledTaskView _(Task Triggers, Errors, Last Run)_ | https://github.com/jellyfin/Swiftfin/pull/1276
- [x] Add Devices view for managing Devices _(Think 'All Devices' in Web)_ | https://github.com/jellyfin/Swiftfin/pull/1277
- [x] Add Users view for managing Users _(All Users + Password Setting / Resetting)_ | https://github.com/jellyfin/Swiftfin/pull/1278
- [ ] Expand User management _(Permissions, Access, Parental Controls)_
- [ ] Migrate all AdminDashboard items into their own Coordinator
- [x] Create HomeView ActiveSessionsIndicator that takes the user into the AdminDashboard | https://github.com/jellyfin/Swiftfin/pull/1282

### ActiveSessionsIndicator
4BF72DC7-FD87-4CF7-B04E-67CD8386840E_4_5005_c

### CODE REVIEW

**Review by LePips — CHANGES_REQUESTED** [review]
This was more digestible when it was mainly task triggers and small work to devices, but now is getting too large for me to review effectively and make comments that apply to future work.

I ask that all new sections be implemented in their own PRs as they are quite independent of one another. This would make my reviews of each section faster and more effective.

**Comment by JPKribs** [comment]
> This was more digestible when it was mainly task triggers and small work to devices, but now is getting too large for me to review effectively and make comments that apply to future work.
> 
> 
> 
> Apologies, butI ask that all new sections be implemented in their own PRs as they are quite independent of one another (sans `xcodeproj` conflicts). This would make my reviews of each section faster and more effective.

Sounds good. For now, a lot of the work builds on other items so I'm just getting this into a single branch. When I'm ready, I'm going to break this out into something more reviewable by section.

**Comment by JPKribs** [comment]
Apologies for that! The primary goal for this branch was to just visibility. But, I completely agree. This is kind of a beast to look at.

**Comment by JPKribs** [comment]
I'm closing this out in favor of smaller, actually manageable PRs. Tracking for this will occur:

https://github.com/jellyfin/Swiftfin/discussions/1283

**Comment by JPKribs** [comment]
I'm closing this out in favor of smaller, actually manageable PRs. Tracking for this will occur:

https://github.com/jellyfin/Swiftfin/discussions/1283

**Pull request closed without merging**
