### PR TITLE
Add libraries as top level tabs on tvOS

### PR DESCRIPTION
**Pull request by jhays**
This PR modifies the MainTabViewModel to request libraries on tvOS on init, and render them as top level Tabs. This replaces the use of the "All Media" tab, and removes LibraryListView from tvOS. It was ugly, and added unnecessary extra clicks to navigate into primary content area. Putting the libraries in top-level tabs feels more familiar from other media apps on tvOS. 

I'm certainly open to feedback if there are any objections to this design change. 

If there are going to be navigation architecture conflicts between this and @LePips pending Coordinator work (I haven't fully reviewed it yet), this PR can hold off and I can rebase after that work is merged- just let me know. 

Simulator Screen Shot - Apple TV 4K (at 1080p) (2nd generation) - 2021-10-16 at 11 03 40

### CODE REVIEW

**Comment by LePips** [comment]
This may break because of my changes in my PR. I would recommend making this a draft so that after my work is merged you can merge it and see if it conflicts or not.

**Comment by LePips** [comment]
It's okay, I converted it. It's underneath "Reviewers"

https://github.blog/changelog/2020-04-08-convert-pull-request-to-draft/

**Comment by acvigue** [comment]
@jhays the other PR has been merged! this looks great!

**Comment by LePips** [comment]
Just an attest to how cool the coordinator system works, I was able to spin up an example in a few minutes. It's on my branch `LePips:jhays-tvos-library-tab-example`.

However, this has me thinking about how this should be implemented:

Should we show _all_ movies as a single library?
 - I'm sure many people have their movies sorted into different libraries.
 - We may need to create an entirely different view for this so that a person can choose which movie library to look at.
 - I don't know how the api handles this. I thought that it just handles _per library_ via the `parentID` parameter.

**Comment by jhays** [comment]
Awesome, thanks! I will review your branch soon to get an understanding. 

My intention was to iterate over Libraries returned by `UserViewsAPI.getUserViews` and display a tab for each Library. So in my case, I happen to have one library for movies title "Movies", and one library titled "TV Shows", but if a user had more than one movies library, I'd intend for a tab to show up for each Library. 

That would be might recommendation for this first pass, certainly there are many options that could be considered going forward.

**Pull request closed without merging**
