### PR TITLE
Live TV Updates

### LINKED ISSUE #538: LiveTV Show times format
Hi !

In LiveTV, show times are shown in 12hrs format.
Is there any way to switch timings to 24hrs format ?

Thanks in advance :)

### PR DESCRIPTION
**Pull request by LePips**
- Re-enable Live TV from the Media view
- Adds Programs view to iOS
	- is the new view presented when selecting Live TV, with Channels as a pill (similar to App Store)
- tvOS will now just present Live TV as a modal instead of a tab root
- Live TV views with progress now handle current program states themselves with timers
	- these views are removed as the underlying collection views remove them, so quite clean
- Lots of `TODO`s, as always
	- mainly have to work towards renaming/refactoring `PosterType` and work on its `TODO` items

tvOS still kind of incomplete as I am unsure of designs, but it always is incomplete at this point.

---

Since this was _my_ first interaction with other media (channels) besides movies/tv shows this allowed me to start thinking about migrating some context-specific things I've done to make things more general, especially for stuff like music/photos.

- Closes #538

### CODE REVIEW

**Comment by LePips** [comment]
@jhays

Since you've done the Live TV work before, I would greatly appreciate a review on this if you would like to check it out.

**Review by jhays — APPROVED** [review]
Exciting to see the progress in the live tv area! Overall everything looks great.

I ran this branch to test it out, one thing I would point out is that the 3 column design with the wide items limits the amount of information that can be communicated in the program titles. It may be worth considering some design adjustments so that the guide info shown on each tile can fit more text within each cell. 

Thanks

Simulator Screenshot - Apple TV 4K (3rd generation) (at 1080p) - 2024-04-16 at 20 15 14

**Review by PangMo5 — APPROVED** [review]

**Review by PangMo5 — DISMISSED** [review]

**Comment by LePips** [comment]
@PangMo5, apologies. Pushed a change right as you approved and then ran into some bad merge conflicts.

**Review by PangMo5 — APPROVED** [review]
np XD

**Comment by avionics75** [comment]
Hi ! Here's a design idea just in case. My french internet provider has this app for TV the design is not that bad. When selecting the channel, the ongoing TV program poster is shown as an illustration with it's title just under. The channel logo is enclosed in a circle on top of the poster that indicates the actual percentage of completion of the program. This design gives minimal information (TV show poster, title, completion and channel logo) but looks pretty neat :-)
IMG_9347

**Pull request merged**
