### PR TITLE
Applying MVVM and Moya on some screens, Changed filter structure

### PR DESCRIPTION
**Pull request by PangMo5**
## Changed
- Add JellyfinAPI 
- Add Filter struct, API related enums
- Add LibraryListViewModel, LibraryViewModel, LibrarySearchViewModel 
- ~Change a specific toolbar to a navigation bar item.~
- Separate LibraryView and LibraryListView.
- Change to present SettingsView as sheet

## Known issues
~- UI cannot be updated after loading when entering LibraryView in MovieItemView and EpisodeItemView.
(Since it works normally when entering from another screen, there seems to be a problem in the life cycle of the MovieItemView and EpisodeItemView.)~ -> Life cycle issues of SwiftUI(NavigationLink) solved as Lazy 

And it seems that there are a lot of @State, @EnvironmentObject, and ObservableObject that are not currently used in a lot of code. It would be nice to increase the performance by refactoring the related code. 

I'm sorry that the commits weren't cleaned up as I modified a lot of code at once.

### CODE REVIEW

**Comment by acvigue** [comment]
All library requests return 401

**Comment by PangMo5** [comment]
> 
> 
> All library requests return 401

It is normal on the simulator, but it seems to return 401 on the actual device.
Could you please give me any Jellyfin API documentation?

**Comment by acvigue** [comment]
Yeah - here's mine. https://play.vigue.me/api-docs/swagger

**Comment by acvigue** [comment]
Try removing the backslashes from the authheader

**Comment by PangMo5** [comment]
> Try removing the backslashes from the authheader
I checked the authHeader, but there was no backslash. 

`MediaBrowser Client="SwiftFin", Device="PangMo5’s iPad", DeviceId="ED8E8ABB-B796-41BC-AFB7-1A2895C0370A", Version="1.0.0", Token="36052aa53fc147db9581f11ace063efd"`

The curious thing is that it works fine in the simulator.

**Comment by PangMo5** [comment]
> Try removing the backslashes from the authheader
I checked the authHeader, but there was no backslash. 

`MediaBrowser Client="SwiftFin", Device="PangMo5’s iPad", DeviceId="ED8E8ABB-B796-41BC-AFB7-1A2895C0370A", Version="1.0.0", Token="xxxxxxxxxxxxxxxxxxxxxxxx"`

The curious thing is that it works fine in the simulator.

**Comment by acvigue** [comment]
When it gets printed in the console - there were backslashes. Let me finish working on this part and i’ll see

**Comment by PangMo5** [comment]
I found the cause.
There seems to be a conflict with the name of the actual device.
If you remove the Device from the authHeader, it works normally.

**Comment by acvigue** [comment]
Try escaping the Device name - I'd rather keep it in as it allows users to see the device name in the web dashboard

**Comment by PangMo5** [comment]
> Try escaping the Device name - I'd rather keep it in as it allows users to see the device name in the web dashboard

Yes it is important.
Let me find out if there is another way.

**Comment by PangMo5** [comment]
https://github.com/jellyfin/jellyfin-sdk-kotlin/blob/47551efa5228026a1e7c81bd1b14c696fd7cc70d/jellyfin-api/src/main/kotlin/org/jellyfin/sdk/api/client/KtorClient.kt#L169

I found the relevant code in the Kotlin SDK and used it.

**Comment by acvigue** [comment]
Please resolve the merge conflict in project.pbxproj and rebase :)

**Comment by PangMo5** [comment]
> Please resolve the merge conflict in project.pbxproj and rebase :)

Resolved conflic. Please merge it.

**Comment by PangMo5** [comment]
Please don't merge this yet.
Let me solve the Know issues.

**Comment by acvigue** [comment]
ok take ur time

**Comment by PangMo5** [comment]
@acvigue fixed all issues, Please merge it :D

**Comment by acvigue** [comment]
Hey! Thanks. I'll look at this when I get off work tmrw.

**Comment by acvigue** [comment]
what exactly is LazyView.swift?

**Comment by PangMo5** [comment]
> what exactly is LazyView.swift?

Like other Views in SwiftUI, NavigationLink is not lazy.
Therefore, Life cycle problems can occur and LazyView helps this.

**Comment by acvigue** [comment]
i see - what problems occur without lazyview. also if the extension is only used in one file, it shouldnt be abstracted away for the sole purpose of abstraction IMO

**Comment by PangMo5** [comment]
> i see - what problems occur without lazyview. also if the extension is only used in one file, it shouldnt be abstracted away for the sole purpose of abstraction IMO

It doesn't matter if you don't abstract it in a personal project. 
But I think it's different in massive projects.
Because extensions of the same function can continue to occur.
I think this method can be used many times later.

**Comment by acvigue** [comment]
lgtm!
only comment -buttons are way too close together on library view

**Comment by acvigue** [comment]
will merge once buttons are respaced :)

**Comment by PangMo5** [comment]
> will merge once buttons are respaced :)

What does the spacing of the buttons mean?  Are you talking about the spacing of the navigation buttons?

**Comment by PangMo5** [comment]
Conflict occurred in LibraryView during Merge.
It was too big conflic, so I chose all of them as my code.
Please check if there is a missing code.

**Comment by acvigue** [comment]
lgtm

**Review by acvigue — APPROVED** [review]

**Pull request merged**
