### PR TITLE
Use homebrew SwiftGen instead of included library

### PR DESCRIPTION
**Pull request by LePips**
Clean up along with https://github.com/jellyfin/Swiftfin/pull/483. `contributing.md` updated with steps and some clarifications.

We already make people use homebrew for Carthage, include `swiftgen` and `swiftformat` as well.

### CODE REVIEW

**Review by PangMo5 — COMMENTED** [review]
How about using Brewfile? It's gonna be a little easier.
Also In the case of swiftformat, we can control the version completely using [mint](https://github.com/yonaskolb/Mint) (Brew only supports the latest version of package).

**Comment by LePips** [comment]
I'm fine with a Brewfile if we want one. The SwiftFormat issue is just an annoying bug that happened with the release yesterday. There's already an issue on the repo since it effects almost everybody and expect it to be fixed soon. After all, this is the first time this has happened since we've used SwiftFormat. I also don't want to default recommending using both Homebrew and Mint, especially just for one dependency. People can download them too through Mint if they know about it and want to.

**Comment by PangMo5** [comment]
Then, I think it would be good to apply Brewfile.

**Review by PangMo5 — APPROVED** [review]
I think it's okay to apply the brewfile in another PR.
Do as you please.

**Comment by LePips** [comment]
I mean, it's just one line `brew install` or one line `brew bundle` with a new file with 3 lines. I'm more inclined to not have one unless we have a more complex build.

**Comment by PangMo5** [comment]
Well, okay. Think about it when we have more dependencies.

**Pull request merged**
