### PR TITLE
Listen for AirPods connection changes

### LINKED ISSUE #1160: When AirPods are removed, media continues playing out loud
### Describe the bug

1. Starting playing media with AirPods in
2. Remove airpods while media is playing
3. Witness media continuing to play out loud, and not automatically pause. (This is a break in behavior with every other popular app such as YouTube, Netflix, Hulu, etc.)

### Application version

1.1(78)

### Where did you install the app from?

App Store

### Device information

iPhone 15 Pro

### OS version

iOS 18 dev beta 4, (this also happened on iOS 17)

### Jellyfin server version

10.8.13

### PR DESCRIPTION
**Pull request by chickdan**
This is by no means the cleanest solution so input is most welcome (primarily on where to put this). Most of this was taken right from Apple's [docs](https://developer.apple.com/documentation/avfaudio/responding_to_audio_route_changes) and from what I've tested it works nicely. 

With this being shared code I do have some concern as I cannot test against an AppleTV. Additionally, I am unsure what else may trigger the `AVAudioSession.routeChangeNotification`.

Closes #1160

### CODE REVIEW

**Review by LePips — APPROVED** [review]
I've thought about making nice wrapper framework for all of the now playing/headphones stuff since they're older APIs and could have some SwiftUI bridges. I'm fine with this currently since I'll be refactoring the entire `VideoPlayerManager` layer.

I'll be able to test and approve later.

**Comment by chickdan** [comment]
Sounds good! Thanks for taking a look!

**Comment by chickdan** [comment]
@LePips I reworked this to use the `MPRemoteCommandCenter` instead which greatly simplifies the code, [Apple docs](https://developer.apple.com/documentation/mediaplayer/mpremotecommand). Hopefully this change will also close #1166.

**Review by LePips — APPROVED** [review]
This works and I've been working in the `MPRemoteCommandCenter` anyways for all the now playing stuff 👍

**Pull request merged**
