### PR TITLE
No Tab Characters and Before First for Argument and Parameter Wrapping

### PR DESCRIPTION
**Pull request by LePips**
Remove `--indent tab` as it just made tab characters that weren't changing anything worthwhile. I realize that these were  causing small linting annoyances like in [this recent commit](https://github.com/jellyfin/Swiftfin/pull/473/commits/1e73e90d4f0eb92329711873661e8ca7c70b0522). This was also prevalent when any change was made on a line, even if the tabs were not.

Change to `before-first` for `--wraparguments` and `--wrapparameters`. This was brought up in [this comment](https://github.com/jellyfin/Swiftfin/discussions/451#discussioncomment-3144747) and after playing with it and seeing the new spacing, I like it. A noticeable change for all API calls and function declarations. Using this style is easy in existing calls when adding new arguments/parameters and for making new argument/parameter lists. You can still develop however you want and then the linter handles it. 

There is the question of the `)` being on the next line instead of being on the same line as the last parameter. After seeing the difference, I have come to prefer it being on the next line since we deal a lot with Combine operators and the indentation would cause confusion.

<details>
<summary>Old argument style</summary>

```swift
UserLibraryAPI.getLatestMedia(userId: SessionManager.main.currentLogin.user.id,
                              fields: [
                                  .primaryImageAspectRatio,
                                  .seriesPrimaryImage,
                                  .seasonUserData,
                                  .overview,
                                  .genres,
                                  .people,
                                  .chapters,
                              ],
                              includeItemTypes: [.movie, .series],
                              enableImageTypes: [.primary, .backdrop, .thumb],
                              enableUserData: true,
                              limit: 8)
```

</details>

<details>
<summary>New argument style</summary>

```swift
UserLibraryAPI.getLatestMedia(
    userId: SessionManager.main.currentLogin.user.id,
    fields: [
        .primaryImageAspectRatio,
        .seriesPrimaryImage,
        .seasonUserData,
        .overview,
        .genres,
        .people,
        .chapters,
    ],
    includeItemTypes: [.movie, .series],
    enableImageTypes: [.primary, .backdrop, .thumb],
    enableUserData: true,
    limit: 8
)
```
</details>

<details>
<summary>Old parameter style</summary>

```swift
    init(item: BaseItemDto,
         title: String,
         subtitle: String?,
         directStreamURL: URL,
         transcodedStreamURL: URL?,
         hlsStreamURL: URL,
         streamType: ServerStreamType,
         response: PlaybackInfoResponse,
         audioStreams: [MediaStream],
         subtitleStreams: [MediaStream],
         chapters: [ChapterInfo],
         selectedAudioStreamIndex: Int,
         selectedSubtitleStreamIndex: Int,
         subtitlesEnabled: Bool,
         autoplayEnabled: Bool,
         overlayType: OverlayType,
         shouldShowPlayPreviousItem: Bool,
         shouldShowPlayNextItem: Bool,
         shouldShowAutoPlay: Bool,
         container: String,
         filename: String?,
         versionName: String?)
    {
```
</details>

<details>
<summary>New parameter style</summary>

```swift
    init(
        item: BaseItemDto,
        title: String,
        subtitle: String?,
        directStreamURL: URL,
        transcodedStreamURL: URL?,
        hlsStreamURL: URL,
        streamType: ServerStreamType,
        response: PlaybackInfoResponse,
        audioStreams: [MediaStream],
        subtitleStreams: [MediaStream],
        chapters: [ChapterInfo],
        selectedAudioStreamIndex: Int,
        selectedSubtitleStreamIndex: Int,
        subtitlesEnabled: Bool,
        autoplayEnabled: Bool,
        overlayType: OverlayType,
        shouldShowPlayPreviousItem: Bool,
        shouldShowPlayNextItem: Bool,
        shouldShowAutoPlay: Bool,
        container: String,
        filename: String?,
        versionName: String?
    ) {
```
</details

### CODE REVIEW

**Comment by LePips** [comment]
Since the action pulls the latest SwiftFormat version and a release was made just a little less than a day ago, there's an issue with the formatter overall. These aren't caught when checking locally.

https://github.com/nicklockwood/SwiftFormat/issues/1216

**Comment by LePips** [comment]
The `macos-latest` action (a change) uses SwiftFormat 0.49.11 and there's an issue with 0.49.12 currently. Just gotta wait for that.

**Comment by PangMo5** [comment]
Is "--self init-only" not working yet?

**Comment by LePips** [comment]
We can't have a rule to safely remove `self` right now. Enabling `redundantSelf` removes `self` where it is necessary within closures. It is known in SwiftFormat that it does not know when it should not remove `self` where necessary, https://github.com/nicklockwood/SwiftFormat/issues/1141.

Before:
```swift
    @ViewBuilder
    func makeStart() -> some View {
        LibraryView(viewModel: self.viewModel, title: title)
    }
```

After:
```swift
    @ViewBuilder
    func makeStart() -> some View {
        LibraryView(viewModel: viewModel, title: title) // Error: Reference to property 'viewModel' in closure requires explicit use of 'self' to make capture semantics explicit
    }
```

**Review by PangMo5 — APPROVED** [review]

**Pull request merged**
