### PR TITLE
Fix iOS Search

### LINKED ISSUE #359: can't search in build  71, and some videos show unairedin bulid 69&71
1. can't search for movies in build  71, it works fine in bulid 69.
2. some videos show unaired in bulid 69&71, but they can be played via web and other jellyfin clients.
3. i hope the jump guestures can work even if the overlay shows up, and more length choices like 30s - 20min or adaptive

### PR DESCRIPTION
**Pull request by LePips**
Must have accidentally referenced the wrong view sometime, oops. I'll consolidate views sometime.

Fixes #359, don't think the unaired is an issue.

### CODE REVIEW

**Comment by PangMo5** [comment]
It's not the latest version, but it could be the same problem.
#400

**Review by PangMo5 — APPROVED** [review]

**Comment by LePips** [comment]
It is yes, I'll add it

**Comment by eightsheep67** [comment]
ios 15.4, app build 74, movie search still not working.

**Comment by PangMo5** [comment]
> ios 15.4, app build 74, movie search still not working.

This PR was merged after build 74 were distributed.
It will be included in the next build.

**Pull request merged**
